root ::= number_list

number_list ::= number (number_list)?

number ::= odd even | even odd

even ::= "0," | "2," | "4," | "6," | "8," | "10," | "12," | "14," | "16," | "18," | "20,"

odd ::= "1," | "3," | "5," | "7," | "9," | "11," | "13," | "15," | "17," | "19,"
