_target_: chemgfn.models.gfn.ChemGFNModule

lora_config:
  _target_: peft.LoraConfig
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]
  r: 16
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  fan_in_fan_out: false

# bnb_config:
#   _target_: transformers.BitsAndBytesConfig
#   load_in_8bit: true

net_config:
  pretrained_model_name_or_path: "meta-llama/Llama-3.2-1B"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.01

# If use bnb, plz use
# _target_: bitsandbytes.optim.PagedAdamW8bit

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${model.net_config.pretrained_model_name_or_path}

scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  _partial_: true
  total_iters: 100000
  power: 1.0

reward:
  _target_: chemgfn.models.reward.Reference_Target_Score_Positive_Mixed_Invalid_Mask
  invalid_start_ratio: 0.2
  invalid_end_ratio: 1.2
  disable_peft: ${model.disable_peft}
  illegal_vocab_penalty: -99
  grammar_disagree_penalty: 0
  sentence_validator:
    _target_: chemgfn.models.validators.Expr24Validator

loss_fn:
  _target_: chemgfn.models.losses.ModifiedSubTBLoss
  subtb_lambda: 1.0
  eps: 1e-8

reward_config:
  test_key: test_value

reward_buffer:
  _target_: chemgfn.utils.gfn_utils.ReplayBuffer
  buffer_size: 500
  sim_tolerance: 0.25
  strict_mode: false
  buffer_aug_value: 0.0

constraint_config:
  min_sentence_len: 1
  max_sentence_len: 7
  grammar_path: ${paths.assets_dir}/24_grammars/general.ebnf
  disable_grammar: false
  processor_type: "prefix"
  legal_tokens: ${paths.assets_dir}/token_list/24_points/general
  illegal_vocab_penalty: -99
  parse_mode: "limited"

training_mixed_config:
  pf_temp_high: 2.0
  pf_temp_low: 0.5
  pf_temp_prob: 0.666
  n_samples: 8
  buffer_mixture_ratio: 0.5
  skip_baseline_sampling: true
  opt_task: false

factor_schedulers:
  reward_temp:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 2
    end: 0.8
    horizon: 50000
  replay_buffer:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 0.2
    end: 0.5
    horizon: 50000
  dataset_buffer:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 0.8
    end: 0.1
    horizon: 50000
  alpha_reference:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 0.0
    end: 0.0
    horizon: 50000
  reference_logits_scale:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 0.0
    end: 0.0
    horizon: 50000
  scaling_factor:
    _target_: chemgfn.models.gfn.Scheduler
    schedule_type: "linear"
    start: 1
    end: 1
    horizon: 5000

compile: false

disable_peft: False
