_target_: chemgfn.models.gfn.ChemGFNModule

lora_config:
  _target_: peft.LoraConfig
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]
  r: 16
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  fan_in_fan_out: false

# bnb_config:
#   _target_: transformers.BitsAndBytesConfig
#   load_in_8bit: true

net_config:
  pretrained_model_name_or_path: "meta-llama/Llama-3.2-1B"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.01

# If use bnb, plz use
# _target_: bitsandbytes.optim.PagedAdamW8bit

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${model.net_config.pretrained_model_name_or_path}

scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  _partial_: true
  total_iters: 100000
  power: 1.0

reward:
  _target_: chemgfn.models.reward.Reference_Target_Score_Positive_Mixed_Invalid_Mask
  valid_sentence_alpha: 1.0
  invalid_start_ratio: 0.2
  invalid_end_ratio: 1.2
  target_score_alpha_base: 0.5
  advantage_alpha: 0.2
  sentence_validator:
    _target_: chemgfn.models.reward.RDKitValidator
    scorer: "logP"

reward_config:
  reward_temp_start: 2
  reward_temp_end: 0.8
  reward_temp_horizon: 50000
  invalid_vocab_alpha: -80
  advantage_alpha_start: 0.01
  advantage_alpha_end: 0.5
  advantage_alpha_horizon: 50000
  scaling_factor_start: 50
  scaling_factor_end: 50
  scaling_factor_horizon: 50000

reward_buffer:
  _target_: chemgfn.utils.gfn_utils.ReplayBuffer
  buffer_size: 200
  sim_tolerance: 0.25

constraint_config:
  min_sentence_len: 2
  max_sentence_len: 10
  grammar_path: ${paths.assets_dir}/SMILES_grammars/generic.ebnf
  apply_grammar: true
  processor_type: "prefix"
  legal_tokens: ${paths.assets_dir}/token_list/SMILES/allowed_llama3.2_1B_allowed_token
  naughty_vocab_alpha: -50
  parse_mode: "limited"

training_mixed_config:
  subtb_lambda: 1.0
  pf_temp_high: 2.0
  pf_temp_low: 0.5
  pf_temp_prob: 0.666
  use_buffer_prob: 0.25
  n_samples: 8
  use_buffer_sample_start_prob: 0.8
  use_buffer_sample_end_prob: 0.2
  buffer_sample_steps: 20000
  buffer_mixture_ratio: 0.5
  skip_baseline_sampling: true
  opt_task: true

compile: false
