defaults:
  - _self_
  - task: smiles_llama3
  - device: gpu
  - hydra: default

seed: 27
exp_name: "smiles_llama3"
save_dir: "runs/${exp_name}"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${exp_name}
  project: "ChemGFN"
  save_dir: ${save_dir}
  offline: False

trainer:
  precision: "bf16-ture"
